name: Building source code

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: sudo apt-get install gperf libjemalloc2 libjemalloc-dev

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build -- -j$(nproc)

    - name: Rename output file
      run: mv build/telly build/telly-linux-amd64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: telly-linux-amd64
        path: build/telly-linux-amd64

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: brew install gperf jemalloc

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build -- -j$(sysctl -n hw.logicalcpu)

    - name: Rename output file
      if: startsWith(github.ref, 'refs/tags/')
      run: mv build/telly build/telly-macos-arm64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: telly-macos-arm64
        path: build/telly-macos-arm64

  on-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        path: ./release-assets

    - name: Publish files
      uses: softprops/action-gh-release@v2
      with:
        files: ./release-assets/telly-*
